name: task-balancer
channels:
  - conda-forge
dependencies:
  - python=3.11
  - nodejs>=20
  - fastapi               # веб-фреймворк
  - uvicorn
  - python-dotenv
  - pip
  - pip:
      - psycopg[binary]>=3.2.0
      - python-dotenv>=1.0.1